### ISSUE TITLE
problem with python 3.10

### ISSUE THREAD

**Issue by it-da-de** [Domain-Connect/DomainConnectDDNS-Python#67] opened 2023-10-28 15:52 UTC
root@it-da:/usr/local/bin# domain-connect-dyndns --config ~/dyndns/settings.txt --domain debian.it-da.de setup
*** domain-connect-dyndns 0.0.9 ***

Traceback (most recent call last):
  File "/usr/local/bin/domain-connect-dyndns", line 33, in <module>
    sys.exit(load_entry_point('domain-connect-dyndns==0.0.9', 'console_scripts', 'domain-connect-dyndns')())
  File "/usr/local/lib/python3.10/dist-packages/dyndns/command_line.py", line 81, in main
    print(domain_setup.main(domain, protocols, settings))
  File "/usr/local/lib/python3.10/dist-packages/dyndns/domain_setup.py", line 19, in main
    config = dc.get_domain_config(domain)
  File "/usr/local/lib/python3.10/dist-packages/domainconnect/domainconnect.py", line 256, in get_domain_config
    ret = self._get_domain_config_for_root(domain_root, domain_connect_api)
  File "/usr/local/lib/python3.10/dist-packages/domainconnect/domainconnect.py", line 282, in _get_domain_config_for_root
    raise NoDomainConnectSettingsException('No Domain Connect config found for {}.'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectSettingsException: No Domain Connect config found for it-da.de.
root@it-da:/usr/local/bin#

**Comment by it-da-de** [comment] 2023-10-28 19:49
I think the problem is on a other side. can anywone help?

**Comment by friendlyFella** [comment] 2023-10-29 13:17
Let me guess: ionos? Have the same issue for a few days now, it's probably on their side again.

**Comment by pawel-kow** [comment] 2023-10-29 13:41
```https://api.domainconnect.ionos.com/v2/it-da.de/settings``` returns error 500
@lianapanatau-ionos can you help? Aren't those endpoints monitored?

**Comment by pawel-kow** [comment] 2023-10-29 13:43
Duplicate of #66

**Closed as completed by pawel-kow** 2023-10-29 13:43 UTC
