### ISSUE TITLE
Error message: Conflict: ... Conflicting records, code 409

### ISSUE THREAD

**Issue by albegadeep** [Domain-Connect/DomainConnectDDNS-Python#12] opened 2019-09-17 16:56 UTC
When my IP address needed updating, I received an error message instead of the expected update:

Conflict: {u'records': [{u'type': u'A', u'host': u'@', u'data': u'[old IP]'}], u'message': u'Conflicting records', u'code': 409}
Could not update DNS record.

What does this mean, and how do I get it to work properly in the future?

**Comment by pawel-kow** [comment] 2019-09-18 06:12
Hi, what is the DNS provider you have the domain with?

The conflict error typically means that there is an A record in the zone for the same host,
however it should not be occurring if the A record comes from the DDNS service itself.

**Comment by albegadeep** [comment] 2019-09-18 17:06
I'm using Ionos. I've always manually updated the A record, and am trying domain-connect to automate it. How do I get domain-connect to set it instead?

**Comment by arnoldblinn** [comment] 2019-09-18 17:22
If one were to run the DDNS project with an existing A Record on the zone, the first run would return the conflict.  Two solutions to this.

1. We could simply use the force parameter
2. We could modify the code to have more user interaction the first time.

As a workaround, if you delete the A record from your zone before running the tool, my guess is that it would work fine.

**Comment by albegadeep** [comment] 2019-09-18 18:00
Yep, deleting the A record, waiting for the TTL timeout (otherwise the tool says everything's fine), and then running it worked. This should probably be documented somewhere. First-time execution offering to force the update would be a good idea, too. Thank you.

**Comment by arnoldblinn** [comment] 2019-09-18 18:02
Glad it resolved; note that these projects are provided as partial sample code, partial helpful utility.  They are open source.  Feel free to do a pull request :-).

**Comment by albegadeep** [comment] 2019-09-18 19:13
As my experience with Python is about 2 dozen lines of code, I REALLY don't think that's a good idea... But thanks for all the help.

**Comment by arnoldblinn** [comment] 2019-09-18 20:08
Fair enough.  I'll let Pawel take care of it here; and I'll get around to updating the Windows version.  This is a good catch.

**Comment by pawel-kow** [comment] 2019-09-19 06:23
@albegadeep 
> I'm using Ionos. I've always manually updated the A record, and am trying domain-connect to automate it. How do I get domain-connect to set it instead?

If you had your original A record when doing `setup`, IONOS would ask you to confirm the conflict and then `update` shall not complain about any conflict anymore as long as you continue updating A record with Domain Connect alone. If you go manually again and change the record it would be a new conflict you'd need to approve it again by doing `setup` or use the force flag which was now implemented by @andreeadima.

**Comment by pawel-kow** [comment] 2019-09-19 06:35
OK, I tested it now and seems that we have a Bug at Ionos about this behavior. The conflict is not detected upfront on `setup` and therefore `update` is hitting the wall. I will take care of it to report and fix.

**Comment by pawel-kow** [comment] 2019-09-19 08:11
OK, it turns our the issue is in DDNS client code. 
As per specification 4.3.2.  when getting an Authorization Code the IP parameter shall be passed to allow for conflict detection.

**Comment by pawel-kow** [comment] 2019-09-19 14:15
Fixed in 0.0.4 release

**Closed by pawel-kow** 2019-09-19 14:15 UTC

**Comment by DarrenBishop** [comment] 2021-05-25 11:31
Recently set this all up with IONOS, seems this issue has returned to some extent; manually changed my A record after initial setup, to double-/paronoia-check it all, but it failed with the 409.

The workaround of deleting the A record and repeating the `setup` fixed; repeated runs of `update` after this, with and without `--ignore-previous-ip`, all worked as expected.

Also observed with IONOS:
On the _Domains & SSL_ page, the _status_ column contains
> External service
> Dynamic DNS

and on the records list page for a domain, the _SERVICE_ column contains
> Dynamic DNS

I have not verified it, but think the 409 might occur when these service(s) are not 'registered'; when you update the record manually, this _Dynamic DNS_ service annotation is removed.

**Comment by pawel-kow** [comment] 2021-05-26 08:19
@DarrenBishop , this is correct and intended behavior at IONOS.
Once a record has been changed to manual it's no longer matching the original consent made by the end-user, so any consecutive update of Dynamic DNS would fail with 409 because of this lacking authorization.
